"""swap recipe image columns to blob storage

Revision ID: bb2842eb6445
Revises: ec4711cd9983
Create Date: 2026-04-28 22:29:27.063329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2842eb6445'
down_revision = 'ec4711cd9983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
