"""add avatar to users

Revision ID: d1e4365e38dc
Revises: 737785a9b367
Create Date: 2026-05-10 13:06:53.919964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e4365e38dc'
down_revision = '737785a9b367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('avatar_mime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_mime')
        batch_op.drop_column('avatar_data')

    # ### end Alembic commands ###
